### ISSUE TITLE
docker image arm64/v8 support

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabs/memtier_benchmark#213]
Example from our automation:
```
root@ip-172-31-50-243:~/# docker run redislabs/memtier_benchmark:edge /usr/local/bin/memtier_benchmark --port 6379 --server localhost --json-out-file oss-standalone-2023-04-18-08-16-47-42c8c61813a8c3287b8acb3155473551a491aa2b-preload__memtier_benchmark-1Mkeys-10B-expire-use-case.json "--data-size" "10" "--command" "SET __key__ __data__" "--command-key-pattern" "P" "-c" "50" "-t" "2" "--hide-histogram" "--key-minimum" "1"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/memtier_benchmark: exec format error
```

**Comment by odidev** [comment]
Hi Team, 

I can see that the CI yaml is already updated last week to release docker images for multi-architecture platforms. However, The CI fails for dockerhub login credentials, here: <https://github.com/RedisLabs/memtier_benchmark/actions/runs/5003623094/jobs/8965084900>. 

Can you please configure the CI to use your DockerHub credentials, so that we can access memtier-benchmark multi-arch docker image on DockerHub?

**Comment by odidev** [comment]
Hi Team, a gentle reminder!!
Are you planning to release multi-arch **memtier_benchmark** docker images?

**Comment by YaacovHazan** [comment]
https://github.com/RedisLabs/memtier_benchmark/pull/225

**Comment by yossigo** [comment]
Just to clarify the status: we currently have a `redislabs/memtier_benchmark:edge` image that can already be tested. A formal version (i.e. `:latest`) will be available on the next release, which is planned to be out soon.
