### ISSUE TITLE
Looking for help on benchmarking duration calculation

### ISSUE THREAD

**Issue by BonjourGit** [RedisLabs/memtier_benchmark#45]
Hi,   
   
In run_benchmark() (memtier_benchmark.cpp), duration is calculated as following:   
`float factor = ((float)(thread_counter - 1) / thread_counter); `   
`duration =  factor * duration +  (float)(*i)->m_cg->get_duration_usec() / thread_counter ;`
   
I would like to understand which theory the above formula is based on in order to obtain the run duration of multiple threads?   
   
Any insight will be very much appreciated!

Thanks.

**Comment by oranagra** [comment]
@BonjourGit this is just a plain average calculation that avoids summing everything into one variable and possibly overflowing (and also avoids pre-dividing every element by count, which can lead to precision loss)

if you'll imagine an average of 3 items, the code does:
```
val = val * 0 + new_val * 1
val = val * 0.5 + new_val *0.5
val = val * (2/3) + new_val * (1/3)
```

at the time of sampling, each thread reports the total requests it sent, and the time it took (which is not necessarily 1 second), so in order to compute the ops/sec we need to divide the total requests by the average time of all workers.

**Comment by BonjourGit** [comment]
@oranagra Thank you very much for the insightful notes! It is clear and helpful.
