### ISSUE TITLE
getting low hit ratio

### ISSUE THREAD

**Issue by agarwalkirti** [RedisLabs/memtier_benchmark#71]
Hi,
I am getting 0 hits/sec if i am running this benchmark on newly installed redis and memcache. Can you explain why this is so and how can i improve the hit percentage. Can you tell for what configurations what will be the result. Please help.

Thank you,
Kirti.

**Comment by yaacovhazan-Redislabs** [comment]
Hi @agarwalkirti, can you please provide more information, the command line that you run, and the output that you got.

**Comment by agarwalkirti** [comment]
I use commandline interface of ubuntu 16.04.
![memtier](https://user-images.githubusercontent.com/30178662/54422425-7ba82780-4734-11e9-964a-d847e614a72c.JPG)

**Comment by yaacovhazan-Redislabs** [comment]
@agarwalkirti, I think your hit ratio is low because of the keys distribution.
by default the ratio of set/get is 1:10 (1 set and 10 get) and the number of requests are 10000
you can try to run with --key-pattern=S:S (Sequential) and set/get ratio of 1:1 to get 100% hit ratio.
another way is to populate the DB with a large number of keys, before running the benchmark.
