### ISSUE TITLE
Can't  run using Docker (error: requests must be greater than zero.)

### ISSUE THREAD

**Issue by dschmidtadv** [RedisLabs/memtier_benchmark#80]
I can't  run memtier_benchmark using Docker
```
docker run --rm memtier_benchmark -s localhost -p 11222 -network networkname  --requests 4
```
 (error: requests must be greater than zero.)
Not sure what I'm doing wrong...

**Comment by RoeyPrat** [comment]
@dschmidtadv 
Everything after `docker run --rm memtier_benchmark` is parameters of memtier_benchmark.
`-network` is not a parameter of memtier_benchmark, therefore memtier_benchmark failed to parse your arguments.
If you meant to use the `--network` parameter of docker, it should be placed before the name of the container (`memtier_benchmark`).
Please see the [docker run documentation](https://docs.docker.com/engine/reference/#network-settings) on how to specify network in docker run.

@YaacovHazan @yaacovhazan-Redislabs I think if memtier_benchmark gets called with an unexpected parameter, it should write just that.

behavior:
```
memtier_benchmark -s localhost -p 11222 -network networkname  --requests 4
error: requests must be greater than zero.
```

expected behavior:
```
memtier_benchmark -s localhost -p 11222 -network networkname  --requests 4
error: unknown parameter -network
```

cheers!

**Comment by yossigo** [comment]
Inactive resolved (?) issue, closing.
